name: ADF CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_call: 
    inputs:
          parametername:
            required: true
            type: string
          CLIENT_ID:
            required: true
            type: string
          TENANT_ID:
            required: true
            type: string
          SUBS_ID:
            required: true
            type: string
          RG:
            required: true
            type: string
          ADF_Name:
            required: true
            type: string
permissions:
  id-token: write
  contents: read             
jobs:
  build:
    name: Build ADF Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.CLIENT_ID }}
          tenant-id: ${{ inputs.TENANT_ID }}
          subscription-id: ${{ inputs.SUBS_ID }}
          enable-AzPSSession: true
  
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
          
      - name: Install npm
        run: npm install

      - name: Validate
        run: npm run build validate $(pwd) /subscriptions/${{ inputs.SUBS_ID }}/resourceGroups/${{ inputs.RG }}/providers/Microsoft.DataFactory/factories/${{ inputs.ADF_Name }}
        
      - name: Generate ARM Template
        run: npm run build export $(pwd) /subscriptions/${{ inputs.SUBS_ID }}/resourceGroups/${{ inputs.RG }}/providers/Microsoft.DataFactory/factories/${{ inputs.ADF_Name }} "ArmTemplate"
      
      - name: List files in current directory
        run: ls -R ArmTemplate/
        
      # - name: Run PowerShell script to update parameters
      #   shell: pwsh
      #   run: |
      #     ./update.ps1 -parameterFile ${{ inputs.parametername }}
          
      - name: List files in current directory
        run: ls
        
      - name: List the updated parameters
        run: cat parameters.updated.json

      # - name: Deploy ARM template
      #   uses: azure/arm-deploy@v1
      #   with:
      #     scope: resourcegroup
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     template: ${{ github.workspace }}/ArmTemplate/ARMTemplateForFactory.json
      #     parameters: ./parameters.updated.json
      #     deploymentMode: Incremental
