name: ADF CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_call: 
    inputs:
          parametername:
            required: true
            type: string
          # CLIENT_ID:
          #   required: true
          #   type: string
          # TENANT_ID:
          #   required: true
          #   type: string
          # SUBS_ID:
          #   required: true
          #   type: string
          # RG:
          #   required: true
          #   type: string
          # ADF_Name:
          #   required: true
          #   type: string
          environment:
            required: true
            type: string
# permissions:
#   id-token: write
#   contents: read             
jobs:
  build:
    name: Build ADF Artifacts
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout template repo
        uses: actions/checkout@v3
        with:
          repository: akshita0809/ADF_Global_Template       
          ref: main                       
          path: template-repo  
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBS_ID }}
          enable-AzPSSession: true
  
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
          
      - name: Install npm
        run: npm install

      - name: Validate
        run: npm run build validate $(pwd) /subscriptions/${{ secrets.SUBS_ID }}/resourceGroups/${{ secrets.RG }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }}
        
      - name: Generate ARM Template
        run: npm run build export $(pwd) /subscriptions/${{ secrets.SUBS_ID }}/resourceGroups/${{ secrets.RG }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }} "ArmTemplate"
      
      - name: List files in current directory
        run: ls -R ArmTemplate/
      - name: List files in current directory
        run: ls downloads/
      # - name: Run PowerShell script to update parameters
      #   shell: pwsh
      #   run: |
      #     ./template-repo/update.ps1 -parameterFile ${{ inputs.parametername }}
          
      
      - name: List the updated parameters
        run: cat ./ArmTemplate/ARMTemplateForFactory.json
      - name: List the updated parameters
        run: cat ./ArmTemplate/ARMTemplateParametersForFactory.json
        
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group validate --resource-group Akshita --template-file ./ArmTemplate/ARMTemplateForFactory.json --parameters ./ArmTemplate/ARMTemplateParametersForFactory.json
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: 41ae3075-2ae0-4d8a-8233-c602b5f8ef28
          resourceGroupName: Akshita
          template: ./ArmTemplate/ARMTemplateForFactory.json
          parameters: ./ArmTemplate/ARMTemplateParametersForFactory.json
          deploymentMode: Incremental
